[0m20:42:48.591928 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6cff6ea830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6d0198e3e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6d000e9d80>]}


============================== 20:42:48.595561 | a95c7912-27e1-47fc-adb5-fe91c484a6da ==============================
[0m20:42:48.595561 [info ] [MainThread]: Running with dbt=1.6.5
[0m20:42:48.596379 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/damajor/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt deps', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m20:42:48.597236 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/damajor/data-architecture-1/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:42:48.598138 [debug] [MainThread]: Command `dbt deps` failed at 20:42:48.597970 after 0.01 seconds
[0m20:42:48.598678 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6cff6ea830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6d000e9a50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6d000e99f0>]}
[0m20:42:48.599208 [debug] [MainThread]: Flushing usage events
[0m15:22:47.710857 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f937d94a860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f937fbfa3e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f937bcf5db0>]}


============================== 15:22:47.715459 | 6dc98850-545b-4ea8-aac2-56e869765dd7 ==============================
[0m15:22:47.715459 [info ] [MainThread]: Running with dbt=1.6.5
[0m15:22:47.716198 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/damajor/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m15:22:47.717084 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/damajor/data-architecture-1/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:22:47.717963 [debug] [MainThread]: Command `dbt deps` failed at 15:22:47.717805 after 0.01 seconds
[0m15:22:47.718481 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f937d94a860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f937bcf5a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f937bcf5a20>]}
[0m15:22:47.719033 [debug] [MainThread]: Flushing usage events
[0m15:24:03.649718 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f929a2e2800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f929c5863e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f929ace1d50>]}


============================== 15:24:03.653453 | 0c0a94b6-cb6b-4ea4-90a3-40f3b2e5dfc9 ==============================
[0m15:24:03.653453 [info ] [MainThread]: Running with dbt=1.6.5
[0m15:24:03.654217 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/damajor/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:24:03.655078 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/damajor/data-architecture-1/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:24:03.655928 [debug] [MainThread]: Command `dbt deps` failed at 15:24:03.655767 after 0.01 seconds
[0m15:24:03.656438 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f929a2e2800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f929ace1a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f929ace19c0>]}
[0m15:24:03.656957 [debug] [MainThread]: Flushing usage events
[0m15:24:45.921786 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb7e5f52830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb7e81f23e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb7e694dd80>]}


============================== 15:24:45.925905 | 96d6f9d7-d5b3-4d7e-9569-4cd4b75cc7c2 ==============================
[0m15:24:45.925905 [info ] [MainThread]: Running with dbt=1.6.5
[0m15:24:45.926648 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/damajor/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt deps', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:24:45.927564 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/damajor/data-architecture-1/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:24:45.928445 [debug] [MainThread]: Command `dbt deps` failed at 15:24:45.928275 after 0.01 seconds
[0m15:24:45.928956 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb7e5f52830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb7e694da50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb7e694d9f0>]}
[0m15:24:45.929519 [debug] [MainThread]: Flushing usage events
[0m20:37:40.711486 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1dbb10220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1d99071f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1d9907190>]}


============================== 20:37:40.715617 | 8fdde25a-1f85-43ad-9267-2f44752e0685 ==============================
[0m20:37:40.715617 [info ] [MainThread]: Running with dbt=1.6.9
[0m20:37:40.716367 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/damajor/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt deps', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:37:40.717308 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/damajor/data-architecture-1/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:37:40.718147 [debug] [MainThread]: Command `dbt deps` failed at 20:37:40.717990 after 0.01 seconds
[0m20:37:40.718646 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1dbb10220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1d9907550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1d99074f0>]}
[0m20:37:40.719162 [debug] [MainThread]: Flushing usage events
[0m21:54:51.374489 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6878518040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f68763331f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6876333190>]}


============================== 21:54:51.378437 | 3aa457e3-94d8-41e7-bf33-19f804af9621 ==============================
[0m21:54:51.378437 [info ] [MainThread]: Running with dbt=1.6.9
[0m21:54:51.379222 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/damajor/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt deps', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:54:51.380131 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/damajor/data-architecture-1/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:54:51.380959 [debug] [MainThread]: Command `dbt deps` failed at 21:54:51.380797 after 0.01 seconds
[0m21:54:51.381525 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6878518040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6876333550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f68763334f0>]}
[0m21:54:51.382115 [debug] [MainThread]: Flushing usage events
